version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: poverty_analysis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: poverty_analysis
      MYSQL_USER: analyst
      MYSQL_PASSWORD: analyst123
    ports:
      - "3306:3306"
    volumes:
      - ./bi.sql:/docker-entrypoint-initdb.d/bi.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
